name: "spring boot application docker image build and push"
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Github repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 'gallinago1981'
          password: ${{ secrets.DOCKER_REPOSITORY_KEY }}
      -
        name: get push tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Gradle build
        run: ./gradlew bootJar -x test -x check
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:
            ghcr.io/gallinago1981/springboot-restapi:${{ env.TAG }},
            ghcr.io/gallinago1981/springboot-restapi:latest
          build-contexts:
            libs=./build/libs